name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Build car service
        run: go get -d ./... && go build ./src/car-service/cmd/car-service

      - name: Test car service
        run: go test -v ./src/car-service/...

      - name: Build payment service
        run: go get -d ./... && go build ./src/payment-service/cmd/payment-service

      - name: Test payment service
        run: go test -v ./src/payment-service/...

      - name: Build rental service
        run: go get -d ./... && go build ./src/rental-service/cmd/rental-service

      - name: Test rental service
        run: go test -v ./src/rental-service/...

      - name: Build gateway service
        run: go get -d ./... && go build ./src/gateway-service/cmd/gateway-service

      - name: Test gateway service
        run: go test -v ./src/gateway-service/...

      - name: Deploy car service
        id: heroku1
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ol.kondraschowa@gmail.com
          heroku_api_key: 39fcbeb6-fc59-4a40-a678-558a922cc19b
          heroku_app_name: rsoi2-car-service
          dockerfile_directory: ./
          dockerfile_name: car-service.Dockerfile

      - name: Deploy payment service
        id: heroku2
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ol.kondraschowa@gmail.com
          heroku_api_key: 39fcbeb6-fc59-4a40-a678-558a922cc19b
          heroku_app_name: rsoi2-payment-service
          dockerfile_directory: ./
          dockerfile_name: payment-service.Dockerfile

      - name: Deploy rental service
        id: heroku3
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ol.kondraschowa@gmail.com
          heroku_api_key: 39fcbeb6-fc59-4a40-a678-558a922cc19b
          heroku_app_name: rsoi2-rental-service
          dockerfile_directory: ./
          dockerfile_name: rental-service.Dockerfile

      - name: Deploy gateway service
        id: herok4
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ol.kondraschowa@gmail.com
          heroku_api_key: 39fcbeb6-fc59-4a40-a678-558a922cc19b
          heroku_app_name: rsoi2-gateway-service
          dockerfile_directory: ./
          dockerfile_name: gateway-service.Dockerfile

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v3/postman/[rsoi] postman_collection.json
          environment: v3/postman/[rsoi][heroku] postman_environment.json
          delayRequest: 1500
          reporters: '[ "cli" ]'
          envVar: '[{ "key":"serviceName", "value":"rsoi2-payment-service" }, { "key":"herokuApiToken", "value":"${{secrets.HEROKU_API_KEY}}" }]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true